# Autogenerated by nbdev

d = { 'settings': {'branch': 'main', 'doc_baseurl': '/', 'doc_host': '', 'git_url': '', 'lib_path': 'morphon_nbdev'},
  'syms': {'morphon_nbdev.core': {'morphon_nbdev.core.foo': ('core.html#foo', 'morphon_nbdev/core.py')}}}
