# Autogenerated by nbdev

d = { 'settings': {'branch': 'main', 'doc_baseurl': '/', 'doc_host': '', 'git_url': '', 'lib_path': 'morphon_nbdev'},
  'syms': { 'morphon_nbdev.core': { 'morphon_nbdev.core.focal_mean': ('core.html#focal_mean', 'morphon_nbdev/core.py'),
                                    'morphon_nbdev.core.focal_std': ('core.html#focal_std', 'morphon_nbdev/core.py'),
                                    'morphon_nbdev.core.global_zscore': ('core.html#global_zscore', 'morphon_nbdev/core.py'),
                                    'morphon_nbdev.core.kernel': ('core.html#kernel', 'morphon_nbdev/core.py'),
                                    'morphon_nbdev.core.load_bathymetry': ('core.html#load_bathymetry', 'morphon_nbdev/core.py'),
                                    'morphon_nbdev.core.local_zscore': ('core.html#local_zscore', 'morphon_nbdev/core.py'),
                                    'morphon_nbdev.core.polygonize_mask': ('core.html#polygonize_mask', 'morphon_nbdev/core.py'),
                                    'morphon_nbdev.core.show_map': ('core.html#show_map', 'morphon_nbdev/core.py')},
            'morphon_nbdev.exceptions': { 'morphon_nbdev.exceptions.GeomorphologyError': ( 'exceptions.html#geomorphologyerror',
                                                                                           'morphon_nbdev/exceptions.py'),
                                          'morphon_nbdev.exceptions.InvalidParameterError': ( 'exceptions.html#invalidparametererror',
                                                                                              'morphon_nbdev/exceptions.py'),
                                          'morphon_nbdev.exceptions.UnprojectedCRSError': ( 'exceptions.html#unprojectedcrserror',
                                                                                            'morphon_nbdev/exceptions.py')}}}
