"""Shared exceptions, raster I/O, focal-neighbourhood statistics, and
standardisation for `morphon_nbdev` -- a self-implemented (no
WhiteboxTools/RichDEM/GRASS/SAGA) port of the Dove/Nanson two-part seabed
geomorphology classification scheme, built for Bass Strait but usable on any
projected bathymetry raster."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['load_bathymetry', 'kernel', 'focal_mean', 'focal_std', 'global_zscore', 'local_zscore', 'polygonize_mask', 'show_map']

# %% ../nbs/00_core.ipynb #a48ccace
from nbdev.showdoc import *

import itertools

import rioxarray  # noqa: F401 -- registers the .rio accessor on xr.DataArray
import xarray as xr
import numpy as np
import geopandas as gpd
import holoviews as hv
import hvplot.pandas  # noqa: F401 -- registers the .hvplot accessor on GeoDataFrame
import hvplot.xarray  # noqa: F401 -- registers the .hvplot accessor on xr.DataArray

from plum import dispatch
from scipy.signal import fftconvolve
from rasterio.features import shapes as rio_shapes
from shapely.geometry import shape as shapely_shape

from .exceptions import *

hv.extension("bokeh")

# %% ../nbs/00_core.ipynb #da4d26dd
def load_bathymetry(path: str, band: int = 1) -> xr.DataArray:
    """Load a bathymetry raster as a 2D DataArray, nodata converted to NaN, and require a projected CRS."""
    da = rioxarray.open_rasterio(path, masked=True).isel(band=band - 1)
    da.name = "depth"
    if da.rio.crs is None or da.rio.crs.is_geographic:
        raise UnprojectedCRSError(
            f"{path} has no projected CRS ({da.rio.crs}); reproject to a projected CRS first."
        )
    return da

# %% ../nbs/00_core.ipynb #3a936ffd-8c34-4aea-af0e-1ad713cf4d60
@dispatch
def kernel(radius: int):
    """Boolean disc mask of the given radius (in cells): True where dy^2+dx^2 <= radius^2."""
    r = int(radius)
    
    x, y = np.ogrid[-r: r+1, -r:r+1]
    dist = x**2 + y**2
    return dist <= r**2

@dispatch
def kernel(inner_radius: int, outer_radius: int):
    """Boolean annulus mask (in cells): True in the ring strictly beyond inner_radius,
    up to and including outer_radius. Equivalent to kernel(outer) with kernel(inner)
    subtracted out; the array is sized to the outer radius."""
    i_r = int(inner_radius)
    o_r = int(outer_radius)

    x, y = np.ogrid[-o_r: o_r+1, -o_r:o_r+1]
    dist = x**2 + y**2
    return (dist > i_r**2) & (dist <= o_r**2)


# %% ../nbs/00_core.ipynb #f21b8ec2-f4ee-4f14-b245-317070763c93
def focal_mean(data: xr.DataArray, radius: int | list) -> xr.DataArray:
    """NaN-aware focal mean over a disc (radius=int) or annulus (radius=[inner, outer]) kernel.

    Cells with no valid data under the kernel (all-NaN neighbourhood, or entirely
    off the raster edge) come back as NaN rather than 0 or inf."""
    k = kernel(radius) if isinstance(radius, int) else kernel(*radius)

    valid_mask = ~np.isnan(data.values)
    values_filled = np.where(valid_mask, data.values, 0)
    valid_count = valid_mask.astype(np.float64)

    sum_values = fftconvolve(values_filled, k, mode="same")
    count_valid = fftconvolve(valid_count, k, mode="same")

    with np.errstate(invalid="ignore", divide="ignore"):
        mean = sum_values / count_valid
    mean[count_valid < 0.5] = np.nan  # no valid cells anywhere in the window

    return data.copy(data=mean)

# %% ../nbs/00_core.ipynb #2b804e30-2523-4842-b7ee-564cbe77252e
def focal_std(data: xr.DataArray, radius: int | list) -> xr.DataArray:
    """NaN-aware focal (windowed) standard deviation, via Var[X] = E[X^2] - E[X]^2.

    Clips negative variance from floating-point cancellation (a near-zero true
    variance can round slightly negative) before the square root, so a flat or
    near-flat neighbourhood gives 0, not NaN."""
    mean = focal_mean(data, radius)
    mean_sq = focal_mean(data ** 2, radius)
    variance = (mean_sq - mean ** 2).clip(min=0)
    return np.sqrt(variance)

# %% ../nbs/00_core.ipynb #34570601-aef4-436a-84bb-0d8b694ef4c6
def global_zscore(data: xr.DataArray) -> xr.DataArray:
    """Whole-field NaN-aware z-score: (data - mean) / std, computed once over the
    entire array -- not windowed. See local_zscore for a windowed version."""
    with np.errstate(invalid="ignore"):
        global_mean = np.nanmean(data.values)
        global_std = np.nanstd(data.values)

    z = (data - global_mean) / global_std
    z.name = "global_zscore"
    return z

# %% ../nbs/00_core.ipynb #1c73fbc2-0f00-433a-8f90-ec5341b79046
def local_zscore(data: xr.DataArray, radius: int | list) -> xr.DataArray:
    """NaN-aware local (windowed) z-score: (data - focal_mean) / focal_std.

    A window with no real local variance (flat neighbourhood, or only one valid
    cell) gives NaN rather than inf or a bogus huge value -- there's no meaningful
    z-score without spread. "No real variance" is judged against a tolerance that
    scales with the local mean's magnitude, not a fixed number: focal_std's own
    E[X^2]-E[X]^2 computation leaves floating-point noise on the order of 1e-8x the
    data's magnitude even when the true variance is exactly 0 (checked empirically
    across depth magnitudes from ~5 to ~5000), so a fixed threshold that works at
    one depth scale silently fails at another."""
    mean = focal_mean(data, radius)
    std = focal_std(data, radius)

    with np.errstate(invalid="ignore", divide="ignore"):
        z = (data - mean) / std

    noise_floor = 1e-8 + 1e-6 * np.abs(mean)
    return z.where(std > noise_floor)

# %% ../nbs/00_core.ipynb #cb3dc9f5-ac49-4e7e-aa7f-1206026eee44
def polygonize_mask(
    mask: np.ndarray, transform, crs, area_threshold_m2: float = 0.0, connectivity: int = 4
) -> gpd.GeoDataFrame:
    """Vectorise a boolean raster mask into a GeoDataFrame, dropping polygons under
    `area_threshold_m2`. `connectivity` (4 or 8) controls whether two True cells that
    only touch diagonally count as one connected feature or two -- disc/annulus
    kernel output can produce diagonal-only touches, so this is worth setting
    deliberately rather than trusting the default."""
    mask_u8 = mask.astype(np.uint8)
    geoms = [
        shapely_shape(geom)
        for geom, value in rio_shapes(mask_u8, mask=mask, transform=transform, connectivity=connectivity)
        if value == 1
    ]
    gdf = gpd.GeoDataFrame(geometry=geoms, crs=crs)
    gdf["area_m2"] = gdf.geometry.area
    gdf = gdf.loc[gdf["area_m2"] >= area_threshold_m2].reset_index(drop=True)
    gdf.insert(0, "featID", np.arange(1, len(gdf) + 1))
    return gdf

# %% ../nbs/00_core.ipynb #382e20fd-2a5d-45d4-97ee-78f1f52fcf86
_DEFAULT_VECTOR_COLORS = [
    "#E08A52",  # Muted Orange (Original)
    "#6FC3E0",  # Soft Sky Blue (Original)
    "#8FD1B8",  # Mint Green (Original)
    "#B5A6E0",  # Lavender Purple (Original)
    "#E26D9B",  # Raspberry Pink
    "#F4D068",  # Warm Yellow
    "#76A035",  # Olive Green
    "#C874D9",  # Orchid Magenta
    "#4A7BB0",  # Steel Blue
    "#D95D5D",  # Terracotta Red
]


def show_map(
    raster: xr.DataArray | None = None,
    vectors: dict[str, gpd.GeoDataFrame] | None = None,
    *,
    title: str = "",
    raster_cmap: str = "viridis",
    raster_clabel: str = "",
    raster_clim: tuple[float, float] | None = None,
    vector_colors: list[str] | None = None,
    frame_width: int = 750,
    frame_height: int = 420,
):
    """Plot a raster alone, vector layer(s) alone, or both overlaid. `vectors` maps a
    legend label to a GeoDataFrame (e.g. {"Bathymetric High": highs, "Bathymetric Low":
    lows}); empty GeoDataFrames are skipped rather than plotted as an empty layer."""
    if raster is None and not vectors:
        raise InvalidParameterError("show_map needs at least `raster` or `vectors` to plot.")

    layers = []
    if raster is not None:
        raster_kwargs = dict(
            x="x", y="y", cmap=raster_cmap, aspect="equal", rasterize=True,
            clabel=raster_clabel, frame_width=frame_width, frame_height=frame_height,
        )
        if raster_clim is not None:
            raster_kwargs["clim"] = raster_clim
        layers.append(raster.hvplot.image(**raster_kwargs))

    if vectors:
        palette = vector_colors or _DEFAULT_VECTOR_COLORS
        for (label, gdf), color in zip(vectors.items(), itertools.cycle(palette)):
            if len(gdf) == 0:
                continue
            layers.append(
                gdf.hvplot(geo=False, color=None, line_color=color, line_width=1.2, fill_alpha=0, label=label)
            )

    if not layers:
        raise InvalidParameterError("show_map has nothing to plot -- all provided vectors were empty.")

    plot = layers[0]
    for layer in layers[1:]:
        plot = plot * layer

    opts = {}
    if title:
        opts["title"] = title
    if vectors:
        opts["legend_position"] = "right"
    if opts:
        plot = plot.opts(**opts)
    return plot
