"""The exception hierarchy for `morphon_nbdev`. Every error raised by this package
inherits from `GeomorphologyError`, so callers can catch one base type instead of
guessing which specific error a given function might raise."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_exceptions.ipynb.

# %% auto #0
__all__ = ['GeomorphologyError', 'UnprojectedCRSError', 'InvalidParameterError']

# %% ../nbs/01_exceptions.ipynb #37e696e8-3828-4f92-b10a-eb9f38749593
class GeomorphologyError(Exception):
    "Base exception for all morphon_nbdev errors."

class UnprojectedCRSError(GeomorphologyError):
    "The input raster has no CRS, or a geographic (lat/lon) one; a projected CRS is required."

class InvalidParameterError(GeomorphologyError):
    "A function argument is the wrong type, out of range, or otherwise unusable, e.g. show_map called with nothing to plot."
